# Generated by Django 3.1.3 on 2020-11-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_data', models.FileField(upload_to='documents/')),
                ('time_uploaded', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('age', models.DateTimeField(default=None, null=True)),
                ('date_of_birth', models.DateTimeField(default=None)),
                ('position', models.CharField(blank=True, default=None, max_length=100)),
                ('department', models.CharField(blank=True, default=None, max_length=100)),
                ('salary', models.FloatField(blank=True, default=None, null=True)),
                ('Date_of_employment', models.DateField(default='2020-01-01', null=True)),
                ('supervisors', models.ManyToManyField(blank=True, to='Employee.Supervisor')),
            ],
        ),
    ]
